
services:
  - type: web
    name: autogig-api
    env: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: LLM_PROVIDER
        value: "huggingface"
      - key: HUGGINGFACE_API_BASE
        value: "https://api-inference.huggingface.co/models"
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: LLM_DEFAULT_MODEL
        value: "microsoft/Phi-3-mini-4k-instruct"

  - type: web
    name: autogig-web
    env: node
    rootDir: web
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      # We'll set NEXT_PUBLIC_API_URL in the Render dashboard after the API is up
