services:
  # ---------- API (FastAPI) ----------
  - type: web
    name: autogig-api
    env: python
    rootDir: api
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true

      # LLM (Hugging Face)
      - key: LLM_PROVIDER
        value: "huggingface"
      - key: HUGGINGFACE_API_BASE
        value: "https://api-inference.huggingface.co/models"
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: LLM_DEFAULT_MODEL
        value: "microsoft/Phi-3-mini-4k-instruct"

  # ---------- Worker (Celery) ----------
  - type: worker
    name: autogig-worker
    env: python
    rootDir: api
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
    startCommand: celery -A app.celery_app worker --loglevel=INFO
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key
